# Generated by Django 4.2.1 on 2023-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('documento', models.CharField(max_length=18)),
                ('contato', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
